### ISSUE TITLE
CH\DHW maximum\minimum temperature entities

### ISSUE THREAD

**Issue by 5A52** [khenderick/esphome-opentherm#3]
Temperatures changed on the boiler, are not reflected on gateway without restart
Looks like they are read once during boot.

**Comment by khenderick** [comment]
I thought these values were basically the boiler's absolute min/max ratings and would thus never change. In my setup they never to, so I made a wrong assumption. Maybe I can make the update interval configurable.

**Comment by khenderick** [comment]
After a bit of thought, decided that I'm just going to always read the min/max values. It only adds two messages to the loop (if the sensors are configured), and covers all use-cases. If the amount of sensors increases too much in the future, I can always make it configurable.

This should be fixed on main.
